HomeValue/Controllers/AdminController.cs
using HomeValue.Data.Interfaces;
using HomeValue.Data.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HomeValue.Controllers
{
    public class AdminController : Controller
    {
        private readonly IAllElements elements;

        public AdminController(IAllElements elements)
        {
            this.elements = elements;
        }
        public IActionResult IndexAdmin()
        {
            return View(elements.Elements);
        }
        public IActionResult Edit(int id)
        {
            return View(elements.Elements.FirstOrDefault(i => i.Id == id));
        }
        [HttpPost]
        public IActionResult Edit(Element element)
        {
            elements.EditElement(element);
            return RedirectToAction("IndexAdmin");
        }
    }
}

HomeValue/Controllers/CountController.cs
using HomeValue.Data.Interfaces;
using HomeValue.Data.Models;
using HomeValue.Data.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HomeValue.Controllers
{
    //В контроллере производяться вычисления и переход на страницу со сметой
    public class CountController : Controller
    {
        private readonly IAllElements elements;
        private readonly Estimate estimate;

        public CountController(IAllElements elements, Estimate estimate)
        {
            this.elements = elements;
            this.estimate = estimate;
        }
        public IActionResult IndexCount()
        {
            return View(estimate);
        }
        public IActionResult ConcreteValue(Parameter param)
        {
            estimate.AddEstimeteItem(param);
            return RedirectToAction("IndexCount");
        }
        public IActionResult WallValue(Parameter param)
        {
            estimate.AddEstimeteItem(param);
            return RedirectToAction("IndexCount");
        }
        public IActionResult RoofValue(Parameter param)
        {
            estimate.AddEstimeteItem(param);
            return RedirectToAction("IndexCount");
        }
        public IActionResult Delete(string name)
        {
            estimate.Delete(name);
            return RedirectToAction("IndexCount");
        }
    }
}

HomeValue/Controllers/HomeController.cs
using HomeValue.Data.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HomeValue.Controllers
{
    //Контроллер позволяет выбрать стоимость чего расчитать
    public class HomeController : Controller
    {
        private readonly IAllElements elements;

        public HomeController(IAllElements elements)
        {
            this.elements = elements;
        }
        public IActionResult Index()
        {
            return View(elements.Elements);
        }
        public IActionResult Distributor(string name)
        {
            if (name == "фундамент")
            {
                var el = elements.Elements.FirstOrDefault(n => n.Name == name);
                return View("Concrete", el);
            }
            else if (name == "стены")
            {
                var el = elements.Elements.FirstOrDefault(n => n.Name == name);
                return View("Wall", el);
            }
            else
            {
                var el = elements.Elements.FirstOrDefault(n => n.Name == name);
                return View("Roof", el);
            }
                
        }
    }
}

HomeValue/Views/Admin/Edit.cshtml
@model Element 
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>
<form method="post" asp-action="Edit">
    <h3>@Model.Name</h3>
    <div>
        <input hidden value="@Model.Name" asp-for="@Model.Name" />
        <label>Цена работы</label>
        <input value="@Model.JobPrice" asp-for="@Model.JobPrice" />
    </div><br />
    <div>
        <label>Цена материала</label>
        <input value="@Model.MaterialPrice" asp-for="@Model.MaterialPrice" />
    </div><br />
    <div>
        <input type="submit" value="сохранить" />
    </div>
</form>

HomeValue/Views/Admin/IndexAdmin.cshtml
@model IEnumerable<Element>

@{
    ViewData["Title"] = "IndexAdmin";
}

<h1>IndexAdmin</h1>
@foreach(var el in Model)
{
    <table>
        <tbody>
            <tr>
                <td><p>@el.Name</p></td>
                <td><a asp-action="Edit" asp-route-id="@el.Id">редактировать</a></td>
            </tr>
        </tbody>
    </table>
}

HomeValue/Views/Count/IndexCount.cshtml
@using HomeValue.Data.Repository
@model Estimate

@{
    ViewData["Title"] = "IndexCount";
}

<h1>IndexCount</h1>
@foreach (var el in Model.Estimates)
{
    <h4>@el.Parameter.Name</h4>
    <p>Объем работ: @el.Volume</p>
    <p>Цена за работу(включая материал): @el.Price</p>
    <form asp-action="Delete" asp-controller="Count" asp-route-name="@el.Name">
        <input type="submit" value="Удалить"/>
    </form>
}
<h4>Итоговая цена @Model.TotalPrice()</h4>

HomeValue/Views/Home/Concrete.cshtml
@model Element 

@{
    ViewData["Title"] = "Concrete";
}

<h1>Concrete</h1>
<form method="post" asp-action="ConcreteValue" asp-controller="Count">
    <input hidden name="Name" value="@Model.Name"/>
    <p>Длинна: <input name="length" value="30" /></p>
    <p>Ширина: <input name="width" value="0,3" /></p>
    <p>Высота: <input name="higth" value="3" /></p>
    <p>Стоимость работы: <input name="JobPrice" value="@Model.JobPrice"/></p>
    <p>Стоимость материала: <input name="MaterialPrice" value="@Model.MaterialPrice" /></p>
    <input type="submit" value="Посчитать" />
</form>

HomeValue/Views/Home/Index.cshtml
@model IEnumerable<Element>

@{
    ViewData["Title"] = "Index";
}

@foreach (var el in Model)
{
    <h3><a asp-action="Distributor" asp-route-name="@el.Name">Посчитать сколько стоит @el.Name</a></h3>
}

HomeValue/Views/Home/Roof.cshtml
@model Element 

@{
    ViewData["Title"] = "Roof";
}

<h1>Roof</h1>
<form method="post" asp-action="RoofValue" asp-controller="Count">
    <input hidden name="Name" value="@Model.Name" />
    <p>Length: <input name="length" value="14" /></p>
    <p>Width: <input name="width" value="10" /></p>
    <p hidden>Higth: <input name="higth" value="1" /></p>
    <p>Стоимость работы: <input name="JobPrice" value="@Model.JobPrice" /></p>
    <p>Стоимость материала: <input name="MaterialPrice" value="@Model.MaterialPrice" /></p>
    <input type="submit" value="Посчитать" />
</form>

HomeValue/Views/Home/Wall.cshtml
@model Element 

@{
    ViewData["Title"] = "Wall";
}

<h1>Wall</h1>
<form method="post" asp-action="WallValue" asp-controller="Count">
    <input hidden name="Name" value="@Model.Name" />
    <p>Length: <input name="length" value="30" /></p>
    <p>Width: <input name="width" value="0,3" /></p>
    <p>Higth: <input name="higth" value="3" /></p>
    <p>Стоимость работы: <input name="JobPrice" value="@Model.JobPrice" /></p>
    <p>Стоимость материала: <input name="MaterialPrice" value="@Model.MaterialPrice" /></p>
    <input type="submit" value="Посчитать" />
</form>

HomeValue/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <a class="navbar-brand" href="#">Carousel</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Count/IndexCount">Смета</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Admin/IndexAdmin">Админка</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div>
        @RenderBody()
    </div>
</body>
</html>